# Use Node.js official image
FROM node:18

# Set working directory
WORKDIR /app

# Copy all files
COPY . .

# Install dependencies
RUN npm install

# Expose port
EXPOSE 5000

# Start the app
CMD ["npm", "start"]
